name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on:macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: make 7zFM
      run: make 7zFM
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
